version: '3.8'

services:
  # Backend service for development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backtest-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=DEBUG
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    networks:
      - backtest-dev-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: backtest-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - backtest-dev-network
    command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

networks:
  backtest-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
